name: samimtest
description: A test project for Samim company.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # local language directions
  flutter_localizations:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  bloc: ^8.1.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  dio: ^4.0.6
  # shimmer
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.1.11
  gen_lang:
    git:
      url: https://github.com/KingWu/gen_lang
      ref: 7ba7548
  flutter_lints: ^2.0.1
  lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - res/images/img_change_language.png
    - res/images/img_world.jpg
    - res/assets/users.json

  fonts:
    - family: IRANSans
      fonts:
        - asset: res/font/iransans/medium.ttf
        - asset: res/font/iransans/bold.ttf
          weight: 700

    - family: SF-Pro-Display
      fonts:
        - asset: res/font/sf-pro-display/regular.otf
        - asset: res/font/sf-pro-display/bold.otf
          weight: 700
